#!/bin/bash

COMMIT_MSG_FILE=$1
COMMIT_MSG=$(cat "$COMMIT_MSG_FILE")


YELLOW='\033[0;33m'
RED='\033[0;31m'
NC='\033[0m'





############################################# SPELL CHECK

MSG_CHECK="$COMMIT_MSG" 
REPO_FILES=$(find . -path "./.git" -prune -o -type f -exec basename {} \;)
MSG_CHECK=$(awk -v a="$MSG_CHECK" -v b="$REPO_FILES" '
BEGIN {
    split(a, arrA, " ");
    split(b, arrB, " ");
    # Create an associative array for words in B
    for (i in arrB) bWords[arrB[i]] = 1;
    # Loop through words in A and print those not in B
    for (i in arrA) {
        if (arrA[i] in bWords) continue;
        if (arrA[i] != "") printf "%s ", arrA[i];
    }
    print "";
}')


if command -v aspell &> /dev/null; then
    SPELL_CHECKER="aspell list"

else
    echo -e "${YELLOW}Warning: No spell checker found. Skipping spell check.${NC}"
    exit 0
fi


SPELL_ERRORS=$(echo "$MSG_CHECK" | $SPELL_CHECKER)
SPELL_ERRORS=$(echo $SPELL_ERRORS | grep -o '\b[a-z][a-zA-Z0-9]*\b') # Remove upercase case

if [ ! -z "$SPELL_ERRORS" ]; then
    echo -e "${RED}Error: Commit message contains spelling errors:${NC}"
    echo "$SPELL_ERRORS"
    exit 1
fi

exit 0
############################################# SPELL CHECK